//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Massage
    {
        public int IDMassage { get; set; }
        public int IDChat { get; set; }
        public string Text { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Chat Chat { get; set; }
    }
}
